apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deploy.label }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.deploy.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: {{ .Values.service.protocol}}
    targetPort: {{ .Values.service.targetPort}}
  selector:
    app: {{ .Values.deploy.label }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
